version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - DOCKER_PASSWORD=Winter@2025
      - DOCKER_USERNAME=revkutty
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - REPOSITORY_URI=061051230050.dkr.ecr.us-east-1.amazonaws.com/tekarch/boacicdrepo1
      - aws ecr get-login-password --region us-east-1 --debug | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Granting execution permissions to Gradle wrapper...
      - echo Cleaning up previous builds...
      - echo "Setting executable permissions for Gradlew scripts..."
      - chmod +x user-management-service/gradlew
      - chmod +x account-service/gradlew
      - chmod +x fund-transfer-service/gradlew
      - echo "Running Gradle build for all microservices..."
      - cd user-management-service && ./gradlew clean build && cd ..
      - cd account-service && ./gradlew clean build && cd ..
      - cd fund-transfer-service && ./gradlew clean build && cd ..


  build:
    commands:
      - # Build the user-management-service Docker image
      - docker build -t user-management-service ./user-management-service
      - # Build the account-service Docker image
      - docker build -t account-service ./account-service
      - # Build the fund-transfer-service Docker image
      - docker build -t fund-transfer-service ./fund-transfer-service


  post_build:
    commands:
      # Tag the images with the repository URI
      - docker tag user-management-service:latest $REPOSITORY_URI:user-management-service-$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag account-service:latest $REPOSITORY_URI:account-service-$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag fund-transfer-service:latest $REPOSITORY_URI:fund-transfer-service-$CODEBUILD_RESOLVED_SOURCE_VERSION
      # Create imagedefinitions.json file for ECS
      - echo '[ { "name": "user-management-service", "imageUri": "'$REPOSITORY_URI':user-management-service-'$CODEBUILD_RESOLVED_SOURCE_VERSION'" }, { "name": "account-service", "imageUri": "'$REPOSITORY_URI':account-service-'$CODEBUILD_RESOLVED_SOURCE_VERSION'" }, { "name": "fund-transfer-service", "imageUri": "'$REPOSITORY_URI':fund-transfer-service-'$CODEBUILD_RESOLVED_SOURCE_VERSION'" } ]' > imagedefinitions.json
      # Push the images to ECR
      - docker push $REPOSITORY_URI:user-management-service-$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPOSITORY_URI:account-service-$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPOSITORY_URI:fund-transfer-service-$CODEBUILD_RESOLVED_SOURCE_VERSION


artifacts:
  files:
    - imagedefinitions.json
    - user-management-service/build/libs/*
    - account-service/build/libs/*
    - fund-transfer-service/build/libs/*
  discard-paths: yes

cache:
  paths:
    - ~/.gradle/caches/**
    - ~/.gradle/wrapper/**